name: Pipeline tools builder
on:
  workflow_dispatch: #TO DELETE after testing
  push:
    branches: main

jobs:
  test_and_build:
    name: Simply run test and build and artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v4

      - name: Run test
        run: make test

      - name: Run build
        run: make build
