name: Release
on:
  workflow_dispatch: #TO DELETE after testing
    inputs:
      release-tag:
        description: "Release tag to test"
        required: true
        type: string
  # push:
  #   tags:
  #     - "v*"

permissions:
  contents: write

jobs:
  test_and_build:
    name: Simply run test and build and artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20

      - name: Display the version of go that we have installed
        run: go version

      - name: Run test
        run: make test

      - name: Run build
        run: make build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag:  "${{ inputs.release-tag }}"
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes
              ./bin/main
            
